import 'package:flutter/material.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/CommunitiesWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/HomeWidget2.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/OverviewTabsWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/SecureAttachmentAccessWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/TaskTypesWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/QualityTabWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/Group7Widget2.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/ThequickestandeasiestwaytogetstartedwithIPinfoistouseoneofourofficiallibrarieswhichareavailableformanypopularprogramminglanguagesandframeworksIfyoudliketowriteyourownlibraryorinteractdirectlywithourAPIthenthedocumentationbelowcanhelpyouWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/FlutLab33352881Widget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/ManageyourprojectsWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/EasyPeasyLemonSqueezyWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/GetSupportWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/CustomerDashboardWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/DocumentationWidget2.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/KeyConceptsWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/DataHostingWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/Rectangle8Widget1.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/Rectangle18Widget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/WorkflowWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/Rectangle9Widget1.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/Ellipse39Widget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/MaskGroupWidget2.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/WritingInstructionsWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/GettingstartedwithIPengineWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/ManageyourAccountWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/TasksTabWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/IntroductiontoIPengineWidget1.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/PricingWidget3.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/Group8Widget2.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/IntroductiontoIPengineWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/FirsttimeusinganAPIWidget.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/Ellipse38Widget.dart';

/* Frame Documentation
    Autogenerated by FlutLab FTF Generator
  */
class DocumentationWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1440.0,
      height: 900.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 526.0,
            top: 743.0,
            right: null,
            bottom: null,
            width: 814.0,
            height: 67.0,
            child:
                ThequickestandeasiestwaytogetstartedwithIPinfoistouseoneofourofficiallibrarieswhichareavailableformanypopularprogramminglanguagesandframeworksIfyoudliketowriteyourownlibraryorinteractdirectlywithourAPIthenthedocumentationbelowcanhelpyouWidget(),
          ),
          Positioned(
            left: 100.0,
            top: 70.0,
            right: null,
            bottom: null,
            width: 224.0,
            height: 50.0,
            child: Group7Widget2(),
          ),
          Positioned(
            left: 917.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 24.0,
            child: HomeWidget2(),
          ),
          Positioned(
            left: 1005.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 54.0,
            height: 24.0,
            child: PricingWidget3(),
          ),
          Positioned(
            left: 1099.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 128.0,
            height: 24.0,
            child: DocumentationWidget2(),
          ),
          Positioned(
            left: 1295.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 45.0,
            height: 45.0,
            child: MaskGroupWidget2(),
          ),
          Positioned(
            left: 1076.0,
            top: 779.0,
            right: null,
            bottom: null,
            width: 264.0,
            height: 51.0,
            child: Group8Widget2(),
          ),
          Positioned(
            left: 1156.0,
            top: 57.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 21.0,
            child: Ellipse38Widget(),
          ),
          Positioned(
            left: 1160.0,
            top: 61.0,
            right: null,
            bottom: null,
            width: 7.0,
            height: 7.0,
            child: Ellipse39Widget(),
          ),
          Positioned(
            left: 588.0,
            top: 263.0,
            right: null,
            bottom: null,
            width: 690.0,
            height: 461.0,
            child: FlutLab33352881Widget(),
          ),
          Positioned(
            left: 541.0,
            top: 198.0,
            right: null,
            bottom: null,
            width: 366.0,
            height: 45.0,
            child: IntroductiontoIPengineWidget(),
          ),
          Positioned(
            left: 541.0,
            top: 243.0,
            right: null,
            bottom: null,
            width: 249.0,
            height: 27.0,
            child: EasyPeasyLemonSqueezyWidget(),
          ),
          Positioned(
            left: 102.0,
            top: 188.0,
            right: null,
            bottom: null,
            width: 334.0,
            height: 642.0,
            child: Rectangle18Widget(),
          ),
          Positioned(
            left: 126.0,
            top: 225.0,
            right: null,
            bottom: null,
            width: 315.0,
            height: 21.0,
            child: GettingstartedwithIPengineWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 474.0,
            right: null,
            bottom: null,
            width: 315.0,
            height: 21.0,
            child: CustomerDashboardWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 689.0,
            right: null,
            bottom: null,
            width: 315.0,
            height: 21.0,
            child: DataHostingWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 768.0,
            right: null,
            bottom: null,
            width: 315.0,
            height: 21.0,
            child: GetSupportWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 253.0,
            right: null,
            bottom: null,
            width: 167.0,
            height: 21.0,
            child: IntroductiontoIPengineWidget1(),
          ),
          Positioned(
            left: 126.0,
            top: 502.0,
            right: null,
            bottom: null,
            width: 155.0,
            height: 21.0,
            child: ManageyourAccountWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 190.0,
            height: 21.0,
            child: SecureAttachmentAccessWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 796.0,
            right: null,
            bottom: null,
            width: 95.0,
            height: 21.0,
            child: CommunitiesWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 287.0,
            right: null,
            bottom: null,
            width: 97.0,
            height: 21.0,
            child: KeyConceptsWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 536.0,
            right: null,
            bottom: null,
            width: 154.0,
            height: 21.0,
            child: ManageyourprojectsWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 604.0,
            right: null,
            bottom: null,
            width: 70.0,
            height: 21.0,
            child: TasksTabWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 321.0,
            right: null,
            bottom: null,
            width: 64.0,
            height: 21.0,
            child: WorkflowWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 570.0,
            right: null,
            bottom: null,
            width: 102.0,
            height: 21.0,
            child: OverviewTabsWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 638.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 21.0,
            child: QualityTabWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 355.0,
            right: null,
            bottom: null,
            width: 135.0,
            height: 21.0,
            child: WritingInstructionsWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 389.0,
            right: null,
            bottom: null,
            width: 77.0,
            height: 21.0,
            child: TaskTypesWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 423.0,
            right: null,
            bottom: null,
            width: 153.0,
            height: 21.0,
            child: FirsttimeusinganAPIWidget(),
          ),
          Positioned(
            left: 420.0,
            top: 198.0,
            right: null,
            bottom: null,
            width: 9.0,
            height: 286.0,
            child: Rectangle9Widget1(),
          ),
          Positioned(
            left: 102.0,
            top: 800.0,
            right: null,
            bottom: null,
            width: 364.0,
            height: 30.0,
            child: Rectangle8Widget1(),
          )
        ]),
      ),
    ));
  }
}
