import 'package:flutter/material.dart';

/* Text Can you imagine all these expensive services been served for free!?
    Autogenerated by FlutLab FTF Generator
  */
class CanyouimaginealltheseexpensiveservicesbeenservedforfreeWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Can you imagine all these expensive services been served for free!?''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 85, 85, 85),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
