import 'package:flutter/material.dart';

/* Rectangle 2341 1
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab23411Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 562.0,
      height: 470.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/9a4b3d05397b020580ce75a8648a94067d7baa7a.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/9a4b3d05397b020580ce75a8648a94067d7baa7a.png",
          color: null,
          fit: BoxFit.cover,
          width: 562.0,
          height: 470.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
