import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Ellipse32Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Vector1Widget1.dart';

/* Group Group 5
    Autogenerated by FlutLab FTF Generator
  */
class Group5Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.545454025268555,
      height: 19.636363983154297,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 1.6363636255264282,
            top: 0.0,
            right: null,
            bottom: null,
            width: 22.909090042114258,
            height: 19.636363983154297,
            child: Ellipse32Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 13.909090995788574,
            right: null,
            bottom: null,
            width: 11.92700481414795,
            height: 5.727272987365723,
            child: Vector1Widget1(),
          )
        ]),
      ),
    );
  }
}
