import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Ellipse35Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Rectangle2Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Group5Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Ellipse34Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Ellipse33Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/ChatwithusWidget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Rectangle3Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Group6Widget1.dart';

/* Group Group 8
    Autogenerated by FlutLab FTF Generator
  */
class Group8Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 264.0,
      height: 51.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 264.0,
            height: 51.0,
            child: Rectangle2Widget1(),
          ),
          Positioned(
            left: 32.0,
            top: 15.0,
            right: null,
            bottom: null,
            width: 112.0,
            height: 20.0,
            child: ChatwithusWidget1(),
          ),
          Positioned(
            left: 213.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 51.0,
            child: Rectangle3Widget1(),
          ),
          Positioned(
            left: 257.0,
            top: 14.0,
            right: null,
            bottom: null,
            width: 34.3636360168457,
            height: 24.545455932617188,
            child: Group6Widget1(),
          ),
          Positioned(
            left: 221.0,
            top: 18.90911865234375,
            right: null,
            bottom: null,
            width: 24.545454025268555,
            height: 19.636363983154297,
            child: Group5Widget1(),
          ),
          Positioned(
            left: 227.0,
            top: 27.0,
            right: null,
            bottom: null,
            width: 3.5,
            height: 3.5,
            child: Ellipse33Widget1(),
          ),
          Positioned(
            left: 232.0,
            top: 27.0,
            right: null,
            bottom: null,
            width: 3.5,
            height: 3.5,
            child: Ellipse34Widget1(),
          ),
          Positioned(
            left: 237.0,
            top: 27.0,
            right: null,
            bottom: null,
            width: 3.5,
            height: 3.5,
            child: Ellipse35Widget1(),
          )
        ]),
      ),
    );
  }
}
