import 'package:flutter/material.dart';

/* Text Innovative Source for IP Address Data
    Autogenerated by FlutLab FTF Generator
  */
class InnovativeSourceforIPAddressDataWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Innovative Source for IP Address Data''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 153, 153, 153),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
