import 'package:flutter/material.dart';

/* Rectangle Rectangle 12
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 52.0,
      height: 4.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: null,
          height: null,
          decoration: BoxDecoration(
            color: Color.fromARGB(255, 0, 0, 0),
          ),
          child: null,
        ),
      ),
    );
  }
}
