import 'package:flutter/material.dart';

/* Rectangle Rectangle 13
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
          width: 456.0,
          height: 478.0,
          decoration: BoxDecoration(
            border: Border.all(
              width: 3.0,
              color: Color.fromARGB(255, 238, 238, 238),
            ),
          ),
          child: Container(
            width: 450.0,
            height: 472.0,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(10.0),
            ),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(10.0),
              child: Container(
                width: null,
                height: null,
                decoration: BoxDecoration(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
                child: null,
              ),
            ),
          )),
    );
  }
}
