import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector 1
    Autogenerated by FlutLab FTF Generator
  */
class Vector1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 11.92700481414795,
      height: 5.727272987365723,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M11.927 5.72727L11.927 0L0.47246 4.93372C-0.345834 5.31818 0.0632564 5.72727 0.47246 5.72727L11.927 5.72727Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
