import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Ellipse Ellipse 32
    Autogenerated by FlutLab FTF Generator
  */
class Ellipse32Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 22.909090042114258,
      height: 19.636363983154297,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M22.9091 9.81818C22.9091 15.2406 17.7807 19.6364 11.4545 19.6364C5.12837 19.6364 0 15.2406 0 9.81818C0 4.39575 5.12837 0 11.4545 0C17.7807 0 22.9091 4.39575 22.9091 9.81818Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
