import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Ellipse 36
    Autogenerated by FlutLab FTF Generator
  */
class Ellipse36Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.0,
      height: 21.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M15 7.38889C15 11.8992 11.7857 16.3333 7.5 21C3.50144 16.3333 0 11.8992 0 7.38889C0 2.87856 3.35786 0 7.5 0C11.6421 0 15 2.87856 15 7.38889Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
        SvgPathPainter.stroke(
          2.0,
          strokeMiterLimit: null,
          strokeCap: null,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M7.5 21L5.98126 22.3013L7.44813 24.0133L8.97306 22.3528L7.5 21ZM13 7.38889C13 9.16125 12.3686 11.0411 11.1374 13.1147C9.90389 15.1923 8.13879 17.3476 6.02694 19.6472L8.97306 22.3528C11.1469 19.9857 13.1318 17.5906 14.5769 15.1569C16.0242 12.7192 17 10.1269 17 7.38889L13 7.38889ZM9.01875 19.6987C7.01726 17.3628 5.24001 15.1972 3.95821 13.0947C2.67655 10.9925 2 9.12598 2 7.38889L-2 7.38889C-2 10.1621 -0.925829 12.7679 0.542875 15.1769C2.01144 17.5857 3.98418 19.9706 5.98126 22.3013L9.01875 19.6987ZM2 7.38889C2 4.08702 4.3556 2 7.5 2L7.5 -2C2.36012 -2 -2 1.67011 -2 7.38889L2 7.38889ZM7.5 2C10.6444 2 13 4.08702 13 7.38889L17 7.38889C17 1.67011 12.6399 -2 7.5 -2L7.5 2Z')
          ..color = Color.fromARGB(255, 240, 134, 75),
      ]),
    );
  }
}
