import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Ellipse Ellipse 33
    Autogenerated by FlutLab FTF Generator
  */
class Ellipse33Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 3.5,
      height: 3.5,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M3.5 1.75C3.5 2.7165 2.7165 3.5 1.75 3.5C0.783502 3.5 0 2.7165 0 1.75C0 0.783502 0.783502 0 1.75 0C2.7165 0 3.5 0.783502 3.5 1.75Z')
          ..color = Color.fromARGB(255, 240, 134, 75),
      ]),
    );
  }
}
