import 'package:flutter/material.dart';

/* Text $0.00 per month, We know it’s expensive!
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab$000permonthWeknowitsexpensiveWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''\$0.00 per month, We know it’s expensive!''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 18.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w600,
        color: Color.fromARGB(255, 240, 134, 75),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
