import 'package:flutter/material.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Group5Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Ellipse35Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Rectangle3Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Rectangle2Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Ellipse34Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Group6Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/ChatwithusWidget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Ellipse33Widget.dart';

/* Group Group 8
    Autogenerated by FlutLab FTF Generator
  */
class Group8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 264.0,
      height: 51.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 264.0,
            height: 51.0,
            child: Rectangle2Widget(),
          ),
          Positioned(
            left: 32.0,
            top: 15.0,
            right: null,
            bottom: null,
            width: 112.0,
            height: 20.0,
            child: ChatwithusWidget(),
          ),
          Positioned(
            left: 213.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 51.0,
            child: Rectangle3Widget(),
          ),
          Positioned(
            left: 257.0,
            top: 14.0,
            right: null,
            bottom: null,
            width: 34.3636360168457,
            height: 24.545455932617188,
            child: Group6Widget(),
          ),
          Positioned(
            left: 221.0,
            top: 18.90911865234375,
            right: null,
            bottom: null,
            width: 24.545454025268555,
            height: 19.636363983154297,
            child: Group5Widget(),
          ),
          Positioned(
            left: 227.0,
            top: 27.0,
            right: null,
            bottom: null,
            width: 3.5,
            height: 3.5,
            child: Ellipse33Widget(),
          ),
          Positioned(
            left: 232.0,
            top: 27.0,
            right: null,
            bottom: null,
            width: 3.5,
            height: 3.5,
            child: Ellipse34Widget(),
          ),
          Positioned(
            left: 237.0,
            top: 27.0,
            right: null,
            bottom: null,
            width: 3.5,
            height: 3.5,
            child: Ellipse35Widget(),
          )
        ]),
      ),
    );
  }
}
