import 'package:flutter/material.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/GetStartedWidget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/FlutLab\$000permonthWeknowitsexpensiveWidget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Rectangle10Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/TheTrustedSourceforIPAddressDataWidget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/WithIPengineyoucanpinpointyouruserslocationscustomizetheirexperiencespreventfraudensurecomplianceandsomuchmoreWidget.dart';

/* Group Group 9
    Autogenerated by FlutLab FTF Generator
  */
class Group9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 442.0,
      height: 281.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 442.0,
            height: 78.0,
            child: TheTrustedSourceforIPAddressDataWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 91.0,
            right: null,
            bottom: null,
            width: 442.0,
            height: 63.0,
            child:
                WithIPengineyoucanpinpointyouruserslocationscustomizetheirexperiencespreventfraudensurecomplianceandsomuchmoreWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 169.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 27.0,
            child: FlutLab$000permonthWeknowitsexpensiveWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 230.0,
            right: null,
            bottom: null,
            width: 156.0,
            height: 51.0,
            child: Rectangle10Widget(),
          ),
          Positioned(
            left: 26.0,
            top: 242.0,
            right: null,
            bottom: null,
            width: 104.0,
            height: 27.0,
            child: GetStartedWidget(),
          )
        ]),
      ),
    );
  }
}
