import 'package:flutter/material.dart';

/* Text IP
    Autogenerated by FlutLab FTF Generator
  */
class IPWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.699999988079071,
      child: Text(
        '''IP''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.171875,
          fontSize: 18.0,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
          color: Color.fromARGB(255, 255, 255, 255),
          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
