import 'package:flutter/material.dart';

/* Text { network: { ip: "8.8.8.8", hostname: "dns.google.", reverse: "2001:4860:4860::8844", asn: "15169" }, location: { country: "United States" }, arin: { name: "LVLT-GOGL-8-8-8", handle: "NET-8-8-8-0-1", parent: "NET-8-0-0-0-1", type: "ALLOCATION", range: "8.8.8.0-8.8.8.255", cidr: "NET-8-8-8-0-1", status: [ "active"
    Autogenerated by FlutLab FTF Generator
  */
class Networkip8888hostnamednsgooglereverse2001486048608844asn15169locationcountryUnitedStatesarinnameLVLTGOGL888handleNET88801parentNET80001typeALLOCATIONrange8880888255cidrNET88801statusactiveWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''{
        network: {
                ip: "8.8.8.8",
                hostname: "dns.google.",
                reverse: "2001:4860:4860::8844",
                asn: "15169"
        },
        location: {
                country: "United States"
        },
        arin: {
                name: "LVLT-GOGL-8-8-8",
                handle: "NET-8-8-8-0-1",
                parent: "NET-8-0-0-0-1",
                type: "ALLOCATION",
                range: "8.8.8.0-8.8.8.255",
                cidr: "NET-8-8-8-0-1",
                status: [
                        "active"''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.7000000817435128,
        fontSize: 14.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
