import 'package:flutter/material.dart';

/* Rectangle Rectangle 3
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 51.0,
        height: 51.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(10.0),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 240, 134, 75),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
