import 'package:flutter/material.dart';

/* Text The Trusted Source for IP Address Data
    Autogenerated by FlutLab FTF Generator
  */
class TheTrustedSourceforIPAddressDataWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''The Trusted Sourcefor IP Address Data''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.0156248728434245,
        fontSize: 30.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
