import 'package:flutter/material.dart';

/* Text With IPengine, you can pinpoint your users’ locations, customize their experiences, prevent fraud, ensure compliance, and so much more.
    Autogenerated by FlutLab FTF Generator
  */
class WithIPengineyoucanpinpointyouruserslocationscustomizetheirexperiencespreventfraudensurecomplianceandsomuchmoreWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''With IPengine, you can pinpoint your users’ locations, customize their experiences, prevent fraud, ensure compliance, and so much more.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 85, 85, 85),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
