import 'package:flutter/material.dart';

/* Text By signing in you accept our, Terms of Service & Privacy Policy
    Autogenerated by FlutLab FTF Generator
  */
class BysigninginyouacceptourTermsofServicePrivacyPolicyWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''By signing in you accept our,
Terms of Service & Privacy Policy''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 10.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 187, 187, 187),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
