import 'package:flutter/material.dart';

/* Text Continue with Google
    Autogenerated by FlutLab FTF Generator
  */
class ContinuewithGoogleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return  Text(
      '''Continue with Google''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 51, 51, 51),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
