import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Ellipse Ellipse 3
    Autogenerated by FlutLab FTF Generator
  */
class Ellipse3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 22.0,
      height: 22.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M22 11C22 17.0751 17.0751 22 11 22C4.92487 22 0 17.0751 0 11C0 4.92487 4.92487 0 11 0C17.0751 0 22 4.92487 22 11Z')
          ..color = Color.fromARGB(255, 247, 114, 57),
      ]),
    );
  }
}
