import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Ellipse Ellipse 27
    Autogenerated by FlutLab FTF Generator
  */
class Ellipse27Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.98046875,
      height: 8.98046875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M8.98047 4.49023C8.98047 6.97012 6.97012 8.98047 4.49023 8.98047C2.01035 8.98047 0 6.97012 0 4.49023C0 2.01035 2.01035 0 4.49023 0C6.97012 0 8.98047 2.01035 8.98047 4.49023Z')
          ..color = Color.fromARGB(255, 221, 221, 221),
      ]),
    );
  }
}
