import 'package:flutter/material.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/IPenginedevWidget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/InnovativeSourceforIPAddressDataWidget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Rectangle1Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Group2Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/BysigninginyouacceptourTermsofServicePrivacyPolicyWidget.dart';

/* Group Group 3
    Autogenerated by FlutLab FTF Generator
  */
class Group3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 424.0,
      height: 517.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 424.0,
            height: 517.0,
            child: Rectangle1Widget(),
          ),
          Positioned(
            left: 98.0,
            top: 359.0,
            right: null,
            bottom: null,
            width: 228.0,
            height: 52.0,
            child: Group2Widget(),
          ),
          Positioned(
            left: 35.0,
            top: 65.0,
            right: null,
            bottom: null,
            width: 224.0,
            height: 18.0,
            child: InnovativeSourceforIPAddressDataWidget(),
          ),
          Positioned(
            left: 131.0,
            top: 446.0,
            right: null,
            bottom: null,
            width: 163.0,
            height: 30.0,
            child: BysigninginyouacceptourTermsofServicePrivacyPolicyWidget(),
          ),
          Positioned(
            left: 35.0,
            top: 33.0,
            right: null,
            bottom: null,
            width: 163.0,
            height: 29.0,
            child: IPenginedevWidget(),
          )
        ]),
      ),
    );
  }
}
