import 'package:flutter/material.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Group1Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Rectangle1Widget1.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/ContinuewithGoogleWidget.dart';

/* Group Group 2
    Autogenerated by FlutLab FTF Generator
  */
class Group2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 228.0,
      height: 52.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 228.0,
            height: 52.0,
            child: Rectangle1Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.13266893855312414;

              double height = constraints.maxHeight * 0.5961538094740647;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.06578947368421052,
                      constraints.maxHeight * 0.21153846153846154,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: Group1Widget(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 62.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 151.0,
            height: 21.0,
            child: ContinuewithGoogleWidget(),
          )
        ]),
      ),
    );
  }
}
