import 'package:flutter/material.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/InsideNodesWidget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Group3Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/InsidelinesWidget.dart';

/* Group Group 4
    Autogenerated by FlutLab FTF Generator
  */
class Group4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 424.0,
      height: 517.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 424.0,
            height: 517.0,
            child: Group3Widget(),
          ),
          Positioned(
            left: 0.000002084343577735126,
            top: 139.0,
            right: null,
            bottom: null,
            width: 424.0,
            height: 149.0,
            child: InsidelinesWidget(),
          ),
          Positioned(
            left: 59.99993896484375,
            top: 128.0,
            right: null,
            bottom: null,
            width: 323.00006103515625,
            height: 171.0,
            child: InsideNodesWidget(),
          )
        ]),
      ),
    );
  }
}
