import 'package:flutter/material.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse5Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse7Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse3Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse4Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse2Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse6Widget.dart';

/* Group Inside Nodes
    Autogenerated by FlutLab FTF Generator
  */
class InsideNodesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 323.00006103515625,
      height: 171.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 22.0,
            child: Ellipse2Widget(),
          ),
          Positioned(
            left: 44.99998474121094,
            top: 149.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 22.0,
            child: Ellipse4Widget(),
          ),
          Positioned(
            left: 131.00001525878906,
            top: 80.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 22.0,
            child: Ellipse5Widget(),
          ),
          Positioned(
            left: 301.00006103515625,
            top: 138.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 22.0,
            child: Ellipse7Widget(),
          ),
          Positioned(
            left: 208.00006103515625,
            top: 22.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 22.0,
            child: Ellipse6Widget(),
          ),
          Positioned(
            left: 83.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 22.0,
            child: Ellipse3Widget(),
          )
        ]),
      ),
    );
  }
}
