import 'package:flutter/material.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line17Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line2Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line5Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line3Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line4Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line29Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line16Widget.dart';

/* Group Inside lines
    Autogenerated by FlutLab FTF Generator
  */
class InsidelinesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 424.0,
      height: 149.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 71.0,
            top: 47.999996185302734,
            right: null,
            bottom: null,
            width: 94.9210205078125,
            height: 0.0,
            child: Line29Widget(),
          ),
          Positioned(
            left: 201.9999542236328,
            top: 80.0,
            right: null,
            bottom: null,
            width: 93.29523468017578,
            height: 0.0,
            child: Line2Widget(),
          ),
          Positioned(
            left: 201.9999542236328,
            top: 80.0,
            right: null,
            bottom: null,
            width: 96.40021514892578,
            height: 0.0,
            child: Line4Widget(),
          ),
          Positioned(
            left: 372.0,
            top: 138.0,
            right: null,
            bottom: null,
            width: 148.67750549316406,
            height: 0.0,
            child: Line5Widget(),
          ),
          Positioned(
            left: 372.0,
            top: 138.0,
            right: null,
            bottom: null,
            width: 77.15568542480469,
            height: 0.0,
            child: Line17Widget(),
          ),
          Positioned(
            left: 201.9999542236328,
            top: 80.0,
            right: null,
            bottom: null,
            width: 110.25879669189453,
            height: 0.0,
            child: Line3Widget(),
          ),
          Positioned(
            left: 70.99992370605469,
            top: 47.999996185302734,
            right: null,
            bottom: null,
            width: 110.57125091552734,
            height: 0.0,
            child: Line16Widget(),
          )
        ]),
      ),
    );
  }
}
