import 'package:flutter/material.dart';

/* Text IPengine.dev
    Autogenerated by FlutLab FTF Generator
  */
class IPenginedevWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''IPengine.dev''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 24.0,
        fontFamily: 'Montserrat',
        fontWeight: FontWeight.w600,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
