import 'package:flutter/material.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line6Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse25Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse27Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line11Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line13Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line7Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line8Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse22Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse29Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse24Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse23Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line15Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse26Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse11Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line9Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse28Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse10Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line10Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line14Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line12Widget.dart';

/* Group Left side dots and lines
    Autogenerated by FlutLab FTF Generator
  */
class LeftsidedotsandlinesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 215.53125,
      height: 204.509765625,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 215.53125,
            top: 76.333984375,
            right: null,
            bottom: null,
            width: 83.86761474609375,
            height: 0.0,
            child: Line6Widget(),
          ),
          Positioned(
            left: 148.177734375,
            top: 127.359375,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse11Widget(),
          ),
          Positioned(
            left: 103.68359375,
            top: 171.853515625,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse22Widget(),
          ),
          Positioned(
            left: 94.703125,
            top: 104.091796875,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse23Widget(),
          ),
          Positioned(
            left: 112.6640625,
            top: 13.470703125,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse24Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 17.9609375,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse25Widget(),
          ),
          Positioned(
            left: 4.490234375,
            top: 122.869140625,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse27Widget(),
          ),
          Positioned(
            left: 26.94140625,
            top: 195.529296875,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse28Widget(),
          ),
          Positioned(
            left: 46.943359375,
            top: 75.92578125,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse29Widget(),
          ),
          Positioned(
            left: 46.943359375,
            top: 0.0,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse26Widget(),
          ),
          Positioned(
            left: 152.66796875,
            top: 52.25,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse10Widget(),
          ),
          Positioned(
            left: 152.66796875,
            top: 131.849609375,
            right: null,
            bottom: null,
            width: 75.24346923828125,
            height: 0.0,
            child: Line7Widget(),
          ),
          Positioned(
            left: 152.66796875,
            top: 131.849609375,
            right: null,
            bottom: null,
            width: 58.31735610961914,
            height: 0.0,
            child: Line9Widget(),
          ),
          Positioned(
            left: 117.154296875,
            top: 17.9609375,
            right: null,
            bottom: null,
            width: 55.714866638183594,
            height: 0.0,
            child: Line10Widget(),
          ),
          Positioned(
            left: 51.43359375,
            top: 80.82421875,
            right: null,
            bottom: null,
            width: 55.24031066894531,
            height: 0.0,
            child: Line11Widget(),
          ),
          Positioned(
            left: 51.43359375,
            top: 80.82421875,
            right: null,
            bottom: null,
            width: 76.333984375,
            height: 0.0,
            child: Line12Widget(),
          ),
          Positioned(
            left: 51.43359375,
            top: 80.82421875,
            right: null,
            bottom: null,
            width: 74.90721893310547,
            height: 0.0,
            child: Line15Widget(),
          ),
          Positioned(
            left: 51.43359375,
            top: 80.82421875,
            right: null,
            bottom: null,
            width: 62.99038314819336,
            height: 0.0,
            child: Line13Widget(),
          ),
          Positioned(
            left: 152.66796875,
            top: 131.849609375,
            right: null,
            bottom: null,
            width: 62.924217224121094,
            height: 0.0,
            child: Line8Widget(),
          ),
          Positioned(
            left: 31.431640625,
            top: 200.01953125,
            right: null,
            bottom: null,
            width: 80.31130981445312,
            height: 0.0,
            child: Line14Widget(),
          )
        ]),
      ),
    );
  }
}
