import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Line Line 23
    Autogenerated by FlutLab FTF Generator
  */
class Line23Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(0.70, -0.72, 0.00, 0.00, 0.72, 0.70, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 53.40601348876953,
          height: 1.0,
          child: SvgWidget(painters: [
            SvgPathPainter.stroke(
              1.0,
              strokeMiterLimit: null,
              strokeCap: null,
              strokeJoin: StrokeJoin.miter,
            )
              ..addPath(
                  'M0 -5.55112e-17L53.406 -5.55112e-17L53.406 -1L0 -1L0 -5.55112e-17Z')
              ..color = Color.fromARGB(255, 221, 221, 221),
          ]),
        ));
  }
}
