import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Line Line 16
    Autogenerated by FlutLab FTF Generator
  */
class Line16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(0.41, 0.91, 0.00, 0.00, -0.91, 0.41, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 110.57125091552734,
          height: 1.0,
          child: SvgWidget(painters: [
            SvgPathPainter.stroke(
              1.0,
              strokeMiterLimit: null,
              strokeCap: null,
              strokeJoin: StrokeJoin.miter,
            )
              ..addPath('M0 0L110.571 0L110.571 -1L0 -1L0 0Z')
              ..color = Color.fromARGB(255, 221, 221, 221),
          ]),
        ));
  }
}
