import 'package:flutter/material.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse21Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse18Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse12Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse16Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line28Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line30Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse13Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line22Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line24Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line18Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse20Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line25Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line19Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line23Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line26Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse9Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse30Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line20Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line27Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse14Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse15Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Ellipse8Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Line21Widget.dart';

/* Group Right side dots and lines
    Autogenerated by FlutLab FTF Generator
  */
class RightsidedotsandlinesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 218.796875,
      height: 201.65234375,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 117.5625,
            right: null,
            bottom: null,
            width: 74.82598114013672,
            height: 0.0,
            child: Line30Widget(),
          ),
          Positioned(
            left: 97.560546875,
            top: 26.94140625,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse12Widget(),
          ),
          Positioned(
            left: 106.541015625,
            top: 104.091796875,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse13Widget(),
          ),
          Positioned(
            left: 93.0703125,
            top: 155.1171875,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse14Widget(),
          ),
          Positioned(
            left: 143.6875,
            top: 65.720703125,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse15Widget(),
          ),
          Positioned(
            left: 168.587890625,
            top: 146.953125,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse16Widget(),
          ),
          Positioned(
            left: 200.8359375,
            top: 192.671875,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse30Widget(),
          ),
          Positioned(
            left: 188.58984375,
            top: 17.9609375,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse18Widget(),
          ),
          Positioned(
            left: 209.81640625,
            top: 89.396484375,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse21Widget(),
          ),
          Positioned(
            left: 152.66796875,
            top: 0.0,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse20Widget(),
          ),
          Positioned(
            left: 41.63671875,
            top: 131.849609375,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse8Widget(),
          ),
          Positioned(
            left: 46.126953125,
            top: 57.96484375,
            right: null,
            bottom: null,
            width: 8.98046875,
            height: 8.98046875,
            child: Ellipse9Widget(),
          ),
          Positioned(
            left: 46.126953125,
            top: 136.33984375,
            right: null,
            bottom: null,
            width: 74.02108001708984,
            height: 0.0,
            child: Line18Widget(),
          ),
          Positioned(
            left: 46.126953125,
            top: 136.33984375,
            right: null,
            bottom: null,
            width: 56.45170211791992,
            height: 0.0,
            child: Line22Widget(),
          ),
          Positioned(
            left: 102.05078125,
            top: 31.431640625,
            right: null,
            bottom: null,
            width: 60.06553649902344,
            height: 0.0,
            child: Line19Widget(),
          ),
          Positioned(
            left: 102.05078125,
            top: 31.431640625,
            right: null,
            bottom: null,
            width: 60.06553649902344,
            height: 0.0,
            child: Line20Widget(),
          ),
          Positioned(
            left: 111.03125,
            top: 108.58203125,
            right: null,
            bottom: null,
            width: 76.0102310180664,
            height: 0.0,
            child: Line21Widget(),
          ),
          Positioned(
            left: 111.03125,
            top: 108.58203125,
            right: null,
            bottom: null,
            width: 53.40601348876953,
            height: 0.0,
            child: Line23Widget(),
          ),
          Positioned(
            left: 193.080078125,
            top: 22.451171875,
            right: null,
            bottom: null,
            width: 65.55315399169922,
            height: 0.0,
            child: Line24Widget(),
          ),
          Positioned(
            left: 214.306640625,
            top: 93.88671875,
            right: null,
            bottom: null,
            width: 70.23941040039062,
            height: 0.0,
            child: Line26Widget(),
          ),
          Positioned(
            left: 214.306640625,
            top: 93.88671875,
            right: null,
            bottom: null,
            width: 70.7994155883789,
            height: 0.0,
            child: Line27Widget(),
          ),
          Positioned(
            left: 205.326171875,
            top: 197.162109375,
            right: null,
            bottom: null,
            width: 55.94765853881836,
            height: 0.0,
            child: Line28Widget(),
          ),
          Positioned(
            left: 157.158203125,
            top: 4.490234375,
            right: null,
            bottom: null,
            width: 66.33143615722656,
            height: 0.0,
            child: Line25Widget(),
          )
        ]),
      ),
    );
  }
}
