import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.109676361083984,
      height: 12.434425354003906,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M13.7868 5.99329C16.6847 5.99329 18.6395 7.25051 19.7542 8.30113L24.1097 4.03C21.4347 1.53278 17.9536 0 13.7868 0C7.75075 0 2.53784 3.47886 0 8.54215L4.98997 12.4344C6.24186 8.69721 9.70567 5.99329 13.7868 5.99329')
          ..color = Color.fromARGB(255, 235, 67, 53),
      ]),
    );
  }
}
