import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 14.815633773803711,
      height: 14.569988250732422,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M14.8156 3.16886C14.8156 1.89443 14.7127 0.964431 14.4898 0L0 0L0 5.75215L8.5052 5.75215C8.33379 7.18164 7.40782 9.33442 5.35005 10.781L5.32121 10.9736L9.90262 14.5382L10.22 14.57C13.1351 11.8661 14.8156 7.88772 14.8156 3.16886')
          ..color = Color.fromARGB(255, 66, 133, 244),
      ]),
    );
  }
}
