import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.006832122802734,
      height: 12.434431076049805,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M13.7868 12.4344C17.9536 12.4344 21.4517 11.0566 24.0068 8.68L19.1369 4.89102C17.8337 5.8038 16.0845 6.44102 13.7868 6.44102C9.70567 6.44102 6.24186 3.73722 5.00711 0L4.82612 0.0154353L0.0622992 3.71822L0 3.89216C2.53784 8.95545 7.75076 12.4344 13.7868 12.4344Z')
          ..color = Color.fromARGB(255, 52, 168, 83),
      ]),
    );
  }
}
