import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.653247833251953,
      height: 13.990952491760254,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.65325 10.0988C6.32745 9.13437 6.1389 8.10096 6.1389 7.03323C6.1389 5.96539 6.32745 4.9321 6.63611 3.96767L6.62748 3.76227L1.80396 0L1.64614 0.0753928C0.600177 2.17653 0 4.53602 0 7.03323C0 9.53045 0.600177 11.8898 1.64614 13.991L6.65325 10.0988')
          ..color = Color.fromARGB(255, 251, 188, 5),
      ]),
    );
  }
}
