import 'package:flutter/material.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Rectangle9Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Group8Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/DocumentationWidget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Group9Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Rectangle8Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Rectangle7Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Ellipse37Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Group7Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/PricingWidget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Networkip8888hostnamednsgooglereverse2001486048608844asn15169locationcountryUnitedStatesarinnameLVLTGOGL888handleNET88801parentNET80001typeALLOCATIONrange8880888255cidrNET88801statusactiveWidget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/MaskGroupWidget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Group10Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/Ellipse36Widget.dart';
import 'package:flutterapp/figma/homepagewidget/widgets/HomeWidget.dart';

/* Frame Home page
    Autogenerated by FlutLab FTF Generator
  */
class HomepageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1440.0,
      height: 900.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 862.0,
            top: 233.0,
            right: null,
            bottom: null,
            width: 468.0,
            height: 477.0,
            child: Rectangle7Widget(),
          ),
          Positioned(
            left: 822.0,
            top: 200.0,
            right: null,
            bottom: null,
            width: 221.0,
            height: 51.0,
            child: Group10Widget(),
          ),
          Positioned(
            left: 917.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 49.0,
            height: 24.0,
            child: HomeWidget(),
          ),
          Positioned(
            left: 1005.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 54.0,
            height: 24.0,
            child: PricingWidget(),
          ),
          Positioned(
            left: 1099.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 126.0,
            height: 24.0,
            child: DocumentationWidget(),
          ),
          Positioned(
            left: 100.0,
            top: 70.0,
            right: null,
            bottom: null,
            width: 224.0,
            height: 50.0,
            child: Group7Widget(),
          ),
          Positioned(
            left: 1295.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 45.0,
            height: 45.0,
            child: MaskGroupWidget(),
          ),
          Positioned(
            left: 933.0,
            top: 57.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 21.0,
            child: Ellipse36Widget(),
          ),
          Positioned(
            left: 937.0,
            top: 61.0,
            right: null,
            bottom: null,
            width: 7.0,
            height: 7.0,
            child: Ellipse37Widget(),
          ),
          Positioned(
            left: 899.0,
            top: 255.0,
            right: null,
            bottom: null,
            width: 286.0,
            height: 456.0,
            child:
                Networkip8888hostnamednsgooglereverse2001486048608844asn15169locationcountryUnitedStatesarinnameLVLTGOGL888handleNET88801parentNET80001typeALLOCATIONrange8880888255cidrNET88801statusactiveWidget(),
          ),
          Positioned(
            left: 1312.0,
            top: 250.0,
            right: null,
            bottom: null,
            width: 9.0,
            height: 65.0,
            child: Rectangle9Widget(),
          ),
          Positioned(
            left: 1076.0,
            top: 779.0,
            right: null,
            bottom: null,
            width: 264.0,
            height: 51.0,
            child: Group8Widget(),
          ),
          Positioned(
            left: 100.0,
            top: 303.0,
            right: null,
            bottom: null,
            width: 442.0,
            height: 281.0,
            child: Group9Widget(),
          ),
          Positioned(
            left: 862.0,
            top: 680.0,
            right: null,
            bottom: null,
            width: 468.0,
            height: 30.0,
            child: Rectangle8Widget(),
          )
        ]),
      ),
    ));
  }
}
