import 'package:flutter/material.dart';

/* Text Chat with us...
    Autogenerated by FlutLab FTF Generator
  */
class ChatwithusWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Chat with us...''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 16.0,
        fontFamily: 'Montserrat',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 153, 153, 153),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
