import 'package:flutter/material.dart';

/* Text Customer Dashboard
    Autogenerated by FlutLab FTF Generator
  */
class CustomerDashboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Customer Dashboard''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w600,
        color: Color.fromARGB(255, 153, 153, 153),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
