import 'package:flutter/material.dart';

/* Text Easy Peasy Lemon Squeezy
    Autogenerated by FlutLab FTF Generator
  */
class EasyPeasyLemonSqueezyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Easy Peasy Lemon Squeezy''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 18.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w600,
        color: Color.fromARGB(255, 85, 85, 85),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
