import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Ellipse Ellipse 39
    Autogenerated by FlutLab FTF Generator
  */
class Ellipse39Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.0,
      height: 7.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M7 3.5C7 5.433 5.433 7 3.5 7C1.567 7 0 5.433 0 3.5C0 1.567 1.567 0 3.5 0C5.433 0 7 1.567 7 3.5Z')
          ..color = Color.fromARGB(255, 240, 134, 75),
      ]),
    );
  }
}
