import 'package:flutter/material.dart';

/* Rectangle 3335288 1
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab33352881Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 690.0,
      height: 461.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/7361782db1de3fb46bc7af85f093b26e38cf0e9c.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/7361782db1de3fb46bc7af85f093b26e38cf0e9c.png",
          color: null,
          fit: BoxFit.cover,
          width: 690.0,
          height: 461.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
