import 'package:flutter/material.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/InnovativeSourceforIPAddressDataWidget3.dart';
import 'package:flutterapp/figma/documentationwidget3/widgets/IPenginedevWidget3.dart';

/* Group Group 7
    Autogenerated by FlutLab FTF Generator
  */
class Group7Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 224.0,
      height: 50.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 163.0,
            height: 29.0,
            child: IPenginedevWidget3(),
          ),
          Positioned(
            left: 0.0,
            top: 32.0,
            right: null,
            bottom: null,
            width: 224.0,
            height: 18.0,
            child: InnovativeSourceforIPAddressDataWidget3(),
          )
        ]),
      ),
    );
  }
}
