import 'package:flutter/material.dart';

/* Text Home
    Autogenerated by FlutLab FTF Generator
  */
class HomeWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Home''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 16.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 85, 85, 85),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
