import 'package:flutter/material.dart';

/* Text Quality Tab
    Autogenerated by FlutLab FTF Generator
  */
class QualityTabWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Quality Tab''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
