import 'package:flutter/material.dart';

/* Rectangle Rectangle 18
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle18Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
          width: 354.0,
          height: 662.0,
          decoration: BoxDecoration(
            border: Border.all(
              width: 10.0,
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            boxShadow: [
              BoxShadow(
                color: Color.fromARGB(25, 0, 0, 0),
                offset: Offset(0.0, 8.0),
                blurRadius: 20.0,
              )
            ],
          ),
          child: Container(
            width: 334.0,
            height: 642.0,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(10.0),
            ),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(10.0),
              child: Container(
                width: null,
                height: null,
                decoration: BoxDecoration(
                  color: Color.fromARGB(255, 249, 249, 249),
                ),
                child: null,
              ),
            ),
          )),
    );
  }
}
