import 'package:flutter/material.dart';

/* Text The quickest and easiest way to get started with IPinfo is to use one of our official libraries, which are available for many popular programming languages and frameworks. If you'd like to write your own library or interact directly with our API then the documentation below can help you.
    Autogenerated by FlutLab FTF Generator
  */
class ThequickestandeasiestwaytogetstartedwithIPinfoistouseoneofourofficiallibrarieswhichareavailableformanypopularprogramminglanguagesandframeworksIfyoudliketowriteyourownlibraryorinteractdirectlywithourAPIthenthedocumentationbelowcanhelpyouWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''The quickest and easiest way to get started with IPinfo is to use one of our official libraries, which are available for many popular programming languages and frameworks. If you\'d like to write your own library or interact directly with our API then the documentation below can help you.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.2499998637608118,
        fontSize: 14.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 85, 85, 85),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
