import 'package:flutter/material.dart';

/* Rectangle The seven deadly sins (1) 1
    Autogenerated by FlutLab FTF Generator
  */
class Thesevendeadlysins11Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-1.00, 0.00, 0.00, 0.00, 0.00, 1.00, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 72.0,
          height: 45.0,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: ExactAssetImage(
                "assets/images/1f08485cd2b1177f2b99d78b212d3ad3eff94168.png",
              ),
              fit: BoxFit.cover,
            ),
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Image.asset(
              "assets/images/1f08485cd2b1177f2b99d78b212d3ad3eff94168.png",
              color: null,
              fit: BoxFit.cover,
              width: 72.0,
              height: 45.0,
              colorBlendMode: BlendMode.dstATop,
            ),
          ),
        ));
  }
}
