import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* BooleanOperation Union
    Autogenerated by FlutLab FTF Generator
  */
class UnionWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.545454025268555,
      height: 19.636363983154297,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M13.0909 19.6364C19.4171 19.6364 24.5455 15.2406 24.5455 9.81818C24.5455 4.39575 19.4171 0 13.0909 0C6.76474 0 1.63636 4.39575 1.63636 9.81818C1.63636 12.5755 2.96239 15.0673 5.09764 16.8506L0.47246 18.8428C-0.345834 19.2273 0.0632564 19.6364 0.47246 19.6364L11.927 19.6364L11.927 19.5863C12.3097 19.6194 12.698 19.6364 13.0909 19.6364Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
