import 'package:flutter/material.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/ChangeOwnerWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Ifadpf9uef89nuqwgerhic41n123e41423nWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Rectangle21Widget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/MaskGroupWidget4.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/FlutLab1922484123Widget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/LogOutWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/AppThemeWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/APIKeyWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/PricingWidget4.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/DragonssingmailcomWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Group8Widget3.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Rectangle24Widget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/EditProfileWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/DocumentationWidget4.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/MaskGroupWidget3.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Rectangle19Widget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/LightThemeSwitchIcon1Widget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/FeedbackWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/SettingsWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/MeliodasAckermanWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/GroupWidget2.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Feedback1Widget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/YourIPWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Group7Widget3.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/HomeWidget3.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Line31Widget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/TemporarilyDeactiveAccountWidget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Rectangle22Widget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Rectangle23Widget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Rectangle25Widget.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Rectangle20Widget.dart';

/* Frame Settings page
    Autogenerated by FlutLab FTF Generator
  */
class SettingspageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1440.0,
      height: 900.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 519.0,
            top: 398.0,
            right: null,
            bottom: null,
            width: 358.0,
            height: 42.0,
            child: Rectangle22Widget(),
          ),
          Positioned(
            left: 519.0,
            top: 465.0,
            right: null,
            bottom: null,
            width: 358.0,
            height: 42.0,
            child: Rectangle23Widget(),
          ),
          Positioned(
            left: 519.0,
            top: 532.0,
            right: null,
            bottom: null,
            width: 358.0,
            height: 42.0,
            child: Rectangle24Widget(),
          ),
          Positioned(
            left: 519.0,
            top: 599.0,
            right: null,
            bottom: null,
            width: 358.0,
            height: 42.0,
            child: Rectangle25Widget(),
          ),
          Positioned(
            left: 100.0,
            top: 70.0,
            right: null,
            bottom: null,
            width: 224.0,
            height: 50.0,
            child: Group7Widget3(),
          ),
          Positioned(
            left: 917.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 24.0,
            child: HomeWidget3(),
          ),
          Positioned(
            left: 1005.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 54.0,
            height: 24.0,
            child: PricingWidget4(),
          ),
          Positioned(
            left: 1099.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 126.0,
            height: 24.0,
            child: DocumentationWidget4(),
          ),
          Positioned(
            left: 1295.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 45.0,
            height: 45.0,
            child: MaskGroupWidget3(),
          ),
          Positioned(
            left: 100.0,
            top: 203.0,
            right: null,
            bottom: null,
            width: 184.0,
            height: 184.0,
            child: MaskGroupWidget4(),
          ),
          Positioned(
            left: 1076.0,
            top: 779.0,
            right: null,
            bottom: null,
            width: 264.0,
            height: 51.0,
            child: Group8Widget3(),
          ),
          Positioned(
            left: 100.0,
            top: 422.0,
            right: null,
            bottom: null,
            width: 244.0,
            height: 36.0,
            child: MeliodasAckermanWidget(),
          ),
          Positioned(
            left: 100.0,
            top: 457.0,
            right: null,
            bottom: null,
            width: 171.0,
            height: 21.0,
            child: DragonssingmailcomWidget(),
          ),
          Positioned(
            left: 100.0,
            top: 506.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 18.0,
            child: YourIPWidget(),
          ),
          Positioned(
            left: 100.0,
            top: 524.0,
            right: null,
            bottom: null,
            width: 103.0,
            height: 24.0,
            child: FlutLab1922484123Widget(),
          ),
          Positioned(
            left: 100.0,
            top: 785.0,
            right: null,
            bottom: null,
            width: 134.0,
            height: 45.0,
            child: Rectangle19Widget(),
          ),
          Positioned(
            left: 100.0,
            top: 720.0,
            right: null,
            bottom: null,
            width: 174.0,
            height: 45.0,
            child: Rectangle20Widget(),
          ),
          Positioned(
            left: 158.0,
            top: 797.0,
            right: null,
            bottom: null,
            width: 54.0,
            height: 21.0,
            child: LogOutWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.015284493234422472;

              double height = constraints.maxHeight * 0.024441691504584417;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.08263888888888889,
                      constraints.maxHeight * 0.8844444444444445,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: GroupWidget2(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 426.0,
            top: 203.0,
            right: null,
            bottom: null,
            width: 627.0,
            height: 0.0,
            child: Line31Widget(),
          ),
          Positioned(
            left: 520.0,
            top: 215.0,
            right: null,
            bottom: null,
            width: 45.0,
            height: 18.0,
            child: APIKeyWidget(),
          ),
          Positioned(
            left: 520.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 50.0,
            height: 18.0,
            child: SettingsWidget(),
          ),
          Positioned(
            left: 158.0,
            top: 730.0,
            right: null,
            bottom: null,
            width: 79.0,
            height: 24.0,
            child: FeedbackWidget(),
          ),
          Positioned(
            left: 119.0,
            top: 732.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 22.0,
            child: Feedback1Widget(),
          ),
          Positioned(
            left: 512.0,
            top: 244.0,
            right: null,
            bottom: null,
            width: 365.0,
            height: 41.0,
            child: Rectangle21Widget(),
          ),
          Positioned(
            left: 529.0,
            top: 255.0,
            right: null,
            bottom: null,
            width: 279.0,
            height: 18.0,
            child: Ifadpf9uef89nuqwgerhic41n123e41423nWidget(),
          ),
          Positioned(
            left: 533.0,
            top: 476.0,
            right: null,
            bottom: null,
            width: 70.0,
            height: 18.0,
            child: AppThemeWidget(),
          ),
          Positioned(
            left: 808.0,
            top: 473.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 26.0,
            child: LightThemeSwitchIcon1Widget(),
          ),
          Positioned(
            left: 533.0,
            top: 409.0,
            right: null,
            bottom: null,
            width: 73.0,
            height: 21.0,
            child: EditProfileWidget(),
          ),
          Positioned(
            left: 533.0,
            top: 544.0,
            right: null,
            bottom: null,
            width: 92.0,
            height: 18.0,
            child: ChangeOwnerWidget(),
          ),
          Positioned(
            left: 533.0,
            top: 611.0,
            right: null,
            bottom: null,
            width: 186.0,
            height: 18.0,
            child: TemporarilyDeactiveAccountWidget(),
          )
        ]),
      ),
    ));
  }
}
