import 'package:flutter/material.dart';

/* Text dragons.sin@gmail.com
    Autogenerated by FlutLab FTF Generator
  */
class DragonssingmailcomWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''dragons.sin@gmail.com''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 85, 85, 85),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
