import 'package:flutter/material.dart';

/* Text 192.24.84.123
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab1922484123Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''192.24.84.123''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 16.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w600,
        color: Color.fromARGB(255, 251, 188, 5),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
