import 'package:flutter/material.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/GroupWidget7.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget9.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget14.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget10.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget16.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget17.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget18.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget15.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget11.dart';

/* Group Group
    Autogenerated by FlutLab FTF Generator
  */
class GroupWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 52.0,
      height: 25.99974822998047,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.0;
              double scaleX = (constraints.maxWidth * percentWidth) / 52.0;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.9999936176562332;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 25.999582290649414;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX, 0, 0, 0, 0, scaleY, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget9(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.31266293158897984;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 16.258472442626953;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.4032293999217686;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 10.48386287689209;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.47134604820838344,
                      constraints.maxHeight * 0.2741917605262455,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget10(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.43257940732515776;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 22.494129180908203;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.6290553192213599;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 16.35527992248535;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.543190075800969,
                      constraints.maxHeight * 0.37094468077864007,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget11(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.4000000220078688;

              double height = constraints.maxHeight * 0.8064464753176427;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.0479999276307913,
                      constraints.maxHeight * 0.09677356199926111,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: GroupWidget7(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.17600000821627104;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 9.152000427246094;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.032257869283143954;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.8386964797973633;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.48799998943622297,
                      constraints.maxHeight * 0.4838678558464763,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget14(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.12007924226614144;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 6.2441205978393555;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.03224446498572849;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.8383479714393616;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.47320072467510516,
                      constraints.maxHeight * 0.2603208917733496,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget15(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.1200793247956496;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 6.244124889373779;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.03224449708084801;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.8383488059043884;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.4773447330181415,
                      constraints.maxHeight * 0.7013018367358317,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget16(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.03212903096125676;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 1.6707096099853516;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.03212934208452923;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.8353548049926758;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.4064627427321214,
                      constraints.maxHeight * 0.10932188257719921,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget17(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.032128987404016346;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 1.67070734500885;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.03212929852686703;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.835353672504425;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.41777398036076474,
                      constraints.maxHeight * 0.863478365615277,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget18(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
