import 'package:flutter/material.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget6.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget8.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget7.dart';

/* Group Group
    Autogenerated by FlutLab FTF Generator
  */
class GroupWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 22.0,
      height: 20.16669464111328,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.500001994046298;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 11.000043869018555;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.04545565675943872;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.9166903495788574;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.20833355730230158,
                      constraints.maxHeight * 0.22727114307213475,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget6(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.29166835004633124;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 6.416703701019287;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.04545591685207331;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.9166955947875977;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.20833355730230158,
                      constraints.maxHeight * 0.5000000945791399,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget7(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.0;
              double scaleX = (constraints.maxWidth * percentWidth) / 22.0;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 1.0;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 20.16669464111328;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX, 0, 0, 0, 0, scaleY, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget8(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
