import 'package:flutter/material.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget12.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/VectorWidget13.dart';

/* Group Group
    Autogenerated by FlutLab FTF Generator
  */
class GroupWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.80000114440918,
      height: 20.967405319213867,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.0;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 20.80000114440918;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 1.0;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 20.967405319213867;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX, 0, 0, 0, 0, scaleY, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget12(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.9399998587828494;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 19.551998138427734;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.9399998671877153;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 19.70935821533203;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.02999995598426474,
                      constraints.maxHeight * 0.029999998180653634,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget13(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
