import 'package:flutter/material.dart';

/* Text ifadp-f9uef-89nuq-wgerh-ic41n-123e4-1423n
    Autogenerated by FlutLab FTF Generator
  */
class Ifadpf9uef89nuqwgerhic41n123e41423nWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''ifadp-f9uef-89nuq-wgerh-ic41n-123e4-1423n''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 85, 85, 85),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
