import 'package:flutter/material.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Thesevendeadlysins11Widget4.dart';

/* Group Mask Group
    Autogenerated by FlutLab FTF Generator
  */
class MaskGroupWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 184.0,
      height: 184.0,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(40, 0, 0, 0),
            offset: Offset(0.0, 3.0),
            blurRadius: 6.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 239.1999969482422,
            top: -2.2737367544323206e-13,
            right: null,
            bottom: null,
            width: 294.3999938964844,
            height: 184.0,
            child: Thesevendeadlysins11Widget4(),
          )
        ]),
      ),
    );
  }
}
