import 'package:flutter/material.dart';
import 'package:flutterapp/figma/settingspagewidget/widgets/Thesevendeadlysins11Widget3.dart';

/* Group Mask Group
    Autogenerated by FlutLab FTF Generator
  */
class MaskGroupWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 45.0,
      height: 45.0,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(40, 0, 0, 0),
            offset: Offset(0.0, 3.0),
            blurRadius: 6.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 58.5,
            top: 0.0,
            right: null,
            bottom: null,
            width: 72.0,
            height: 45.0,
            child: Thesevendeadlysins11Widget3(),
          )
        ]),
      ),
    );
  }
}
