import 'package:flutter/material.dart';

/* Rectangle Rectangle 21
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle21Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 365.0,
        height: 41.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 221, 221, 221),
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(10.0),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 245, 245, 245),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
