import 'package:flutter/material.dart';

/* Rectangle The seven deadly sins (1) 1
    Autogenerated by FlutLab FTF Generator
  */
class Thesevendeadlysins11Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-1.00, 0.00, 0.00, 0.00, 0.00, 1.00, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: ClipRRect(
          borderRadius: BorderRadius.circular(20.0),
          child: Container(
            width: 294.3999938964844,
            height: 184.0,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(20.0),
              image: DecorationImage(
                image: ExactAssetImage(
                  "assets/images/1f08485cd2b1177f2b99d78b212d3ad3eff94168.png",
                ),
                fit: BoxFit.cover,
              ),
            ),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(20.0),
              child: Image.asset(
                "assets/images/1f08485cd2b1177f2b99d78b212d3ad3eff94168.png",
                color: null,
                fit: BoxFit.cover,
                width: 294.3999938964844,
                height: 184.0,
                colorBlendMode: BlendMode.dstATop,
              ),
            ),
          ),
        ));
  }
}
