import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.152000427246094,
      height: 1.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M8.736 0L0.416 0C0.18625 0 0 0.187749 0 0.419348C0 0.650948 0.18625 0.838696 0.416 0.838696L8.736 0.838696C8.96575 0.838696 9.152 0.650948 9.152 0.419348C9.152 0.187749 8.96575 0 8.736 0Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
