import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.416703701019287,
      height: 1.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M5.95835 0L0.458348 0C0.205004 0 0 0.205003 0 0.458347C0 0.711691 0.205004 0.916696 0.458348 0.916696L5.95835 0.916696C6.2117 0.916696 6.4167 0.711691 6.4167 0.458347C6.4167 0.205003 6.2117 0 5.95835 0Z')
          ..color = Color.fromARGB(255, 0, 0, 0),
      ]),
    );
  }
}
