import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget18 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(0.70, 0.71, 0.00, 0.00, -0.70, 0.71, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 1.67070734500885,
          height: 1.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M1.25303 0L0.417677 0C0.187 0 0 0.187 0 0.417677C0 0.648353 0.187 0.835354 0.417677 0.835354L1.25303 0.835354C1.48371 0.835354 1.67071 0.648353 1.67071 0.417677C1.67071 0.187 1.48371 0 1.25303 0Z')
              ..color = Color.fromARGB(255, 255, 255, 255),
          ]),
        ));
  }
}
