import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(0.97, 0.26, 0.00, 0.00, -0.26, 0.97, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 6.244124889373779,
          height: 1.0001184940338135,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M5.82785 0L0.416275 0C0.186373 0 0 0.187671 0 0.419174C0 0.650678 0.186373 0.838349 0.416275 0.838349L5.82785 0.838349C6.05775 0.838349 6.24412 0.650678 6.24412 0.419174C6.24412 0.187671 6.05775 0 5.82785 0Z')
              ..color = Color.fromARGB(255, 255, 255, 255),
          ]),
        ));
  }
}
