import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.80000114440918,
      height: 20.967405319213867,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M20.8 10.4837C20.8 4.69371 16.1438 0 10.4 0C4.65624 0 0 4.69371 0 10.4837C0 16.2737 4.65624 20.9674 10.4 20.9674C16.1438 20.9674 20.8 16.2737 20.8 10.4837Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
