import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 52.0,
      height: 25.999582290649414,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M39.104 0L12.896 0C5.77374 0 0 5.8202 0 12.9998C0 20.1794 5.77374 25.9996 12.896 25.9996L39.104 25.9996C46.2263 25.9996 52 20.1794 52 12.9998C52 5.8202 46.2263 0 39.104 0Z')
          ..setLinearGradient(
            startX: 45.34399923316563,
            startY: 1.0139832465326062,
            endX: 21.94399926437236,
            endY: 25.999581633598517,
            colors: [
              Color.fromARGB(255, 255, 233, 145),
              Color.fromARGB(255, 255, 196, 0)
            ],
            colorStops: [0.0, 1.0],
          ),
      ]),
    );
  }
}
