import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 11.000043869018555,
      height: 1.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.458348 0.91669L10.5417 0.91669C10.795 0.91669 11 0.711688 11 0.458345C11 0.205003 10.795 0 10.5417 0L0.458348 0C0.205004 0 0 0.205003 0 0.458345C4.29688e-05 0.711731 0.205047 0.91669 0.458348 0.91669Z')
          ..color = Color.fromARGB(255, 0, 0, 0),
      ]),
    );
  }
}
