import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 19.551998138427734,
      height: 19.70935821533203,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          3.0,
          strokeMiterLimit: null,
          strokeCap: null,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M9.776 1.5C14.3354 1.5 18.052 5.22916 18.052 9.85468L21.052 9.85468C21.052 3.59502 16.0149 -1.5 9.776 -1.5L9.776 1.5ZM18.052 9.85468C18.052 14.4802 14.3354 18.2094 9.776 18.2094L9.776 21.2094C16.0149 21.2094 21.052 16.1143 21.052 9.85468L18.052 9.85468ZM9.776 18.2094C5.2166 18.2094 1.5 14.4802 1.5 9.85468L-1.5 9.85468C-1.5 16.1143 3.53712 21.2094 9.776 21.2094L9.776 18.2094ZM1.5 9.85468C1.5 5.22916 5.2166 1.5 9.776 1.5L9.776 -1.5C3.53712 -1.5 -1.5 3.59502 -1.5 9.85468L1.5 9.85468Z')
          ..color = Color.fromARGB(255, 245, 245, 245),
      ]),
    );
  }
}
