import 'package:flutter/material.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/LeftsidedotsandlinesWidget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/Group4Widget.dart';
import 'package:flutterapp/figma/loginpagewidget/widgets/RightsidedotsandlinesWidget.dart';

/* Frame Login page
    Autogenerated by FlutLab FTF Generator
  */
class LoginpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 1440.0,
        height: 900.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(20.0),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Container(
                  width: null,
                  height: null,
                  decoration: BoxDecoration(
                    color: Color.fromARGB(255, 250, 250, 250),
                  ),
                  child: null,
                ),
                Positioned(
                  left: 293.0,
                  top: 346.0,
                  right: null,
                  bottom: null,
                  width: 215.53125,
                  height: 204.509765625,
                  child: LeftsidedotsandlinesWidget(),
                ),
                Positioned(
                  left: 916.0,
                  top: 293.0,
                  right: null,
                  bottom: null,
                  width: 218.796875,
                  height: 201.65234375,
                  child: RightsidedotsandlinesWidget(),
                ),
                Positioned(
                  left: 508.0,
                  top: 173.0,
                  right: null,
                  bottom: null,
                  width: 424.0,
                  height: 517.0,
                  child: Group4Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
