import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/CanyouimaginealltheseexpensiveservicesbeenservedforfreeWidget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Rectangle15Widget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/PricingWidget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Rectangle12Widget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Rectangle13Widget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Rectangle14Widget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Ellipse36Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/MaskGroupWidget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Ellipse37Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Group7Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Rectangle17Widget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Group8Widget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/FlutLab\$000FreeWidget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Rectangle16Widget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/Rectangle11Widget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/GeolocationASNAbusePrivacyDetectionHostedDomainsCarrierCompanyIPRangesWidget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/FlutLab23411Widget.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/HomeWidget1.dart';
import 'package:flutterapp/figma/pricingwidget2/widgets/DocumentationWidget1.dart';

/* Frame Pricing
    Autogenerated by FlutLab FTF Generator
  */
class PricingWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1440.0,
      height: 900.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 111.0,
            top: 348.0,
            right: null,
            bottom: null,
            width: 450.0,
            height: 472.0,
            child: Rectangle13Widget(),
          ),
          Positioned(
            left: 100.0,
            top: 70.0,
            right: null,
            bottom: null,
            width: 224.0,
            height: 50.0,
            child: Group7Widget1(),
          ),
          Positioned(
            left: 917.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 24.0,
            child: HomeWidget1(),
          ),
          Positioned(
            left: 1005.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 57.0,
            height: 24.0,
            child: PricingWidget1(),
          ),
          Positioned(
            left: 1099.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 126.0,
            height: 24.0,
            child: DocumentationWidget1(),
          ),
          Positioned(
            left: 1295.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 45.0,
            height: 45.0,
            child: MaskGroupWidget1(),
          ),
          Positioned(
            left: 1076.0,
            top: 779.0,
            right: null,
            bottom: null,
            width: 264.0,
            height: 51.0,
            child: Group8Widget1(),
          ),
          Positioned(
            left: 111.0,
            top: 195.0,
            right: null,
            bottom: null,
            width: 450.0,
            height: 162.0,
            child: Rectangle11Widget(),
          ),
          Positioned(
            left: 161.0,
            top: 226.0,
            right: null,
            bottom: null,
            width: 144.0,
            height: 36.0,
            child: FlutLab$000FreeWidget(),
          ),
          Positioned(
            left: 161.0,
            top: 265.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 4.0,
            child: Rectangle12Widget(),
          ),
          Positioned(
            left: 161.0,
            top: 288.0,
            right: null,
            bottom: null,
            width: 350.0,
            height: 42.0,
            child:
                CanyouimaginealltheseexpensiveservicesbeenservedforfreeWidget(),
          ),
          Positioned(
            left: 778.0,
            top: 215.0,
            right: null,
            bottom: null,
            width: 562.0,
            height: 470.0,
            child: FlutLab23411Widget(),
          ),
          Positioned(
            left: 176.0,
            top: 400.0,
            right: null,
            bottom: null,
            width: 316.0,
            height: 47.0,
            child: Rectangle14Widget(),
          ),
          Positioned(
            left: 176.0,
            top: 499.0,
            right: null,
            bottom: null,
            width: 316.0,
            height: 47.0,
            child: Rectangle15Widget(),
          ),
          Positioned(
            left: 176.0,
            top: 598.0,
            right: null,
            bottom: null,
            width: 316.0,
            height: 47.0,
            child: Rectangle16Widget(),
          ),
          Positioned(
            left: 176.0,
            top: 697.0,
            right: null,
            bottom: null,
            width: 316.0,
            height: 47.0,
            child: Rectangle17Widget(),
          ),
          Positioned(
            left: 210.0,
            top: 410.0,
            right: null,
            bottom: null,
            width: 157.0,
            height: 369.0,
            child:
                GeolocationASNAbusePrivacyDetectionHostedDomainsCarrierCompanyIPRangesWidget(),
          ),
          Positioned(
            left: 1026.0,
            top: 57.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 21.0,
            child: Ellipse36Widget1(),
          ),
          Positioned(
            left: 1030.0,
            top: 61.0,
            right: null,
            bottom: null,
            width: 7.0,
            height: 7.0,
            child: Ellipse37Widget1(),
          )
        ]),
      ),
    ));
  }
}
